# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import example2 as module_0


def test_case_0():
    int_0 = -183
    str_0 = module_0.triangle(int_0, int_0, int_0)
    assert str_0 == "Equilateral triangle"


def test_case_1():
    bytes_0 = b"\x14\xb5c\xe7\x8fHI\xcd\xd2\xe9\xab"
    none_type_0 = None
    str_0 = module_0.triangle(bytes_0, none_type_0, none_type_0)
    assert str_0 == "Isosceles triangle"


def test_case_2():
    bool_0 = False
    bool_1 = True
    bool_2 = True
    int_0 = -1141
    str_0 = module_0.triangle(bool_0, bool_0, int_0)
    assert str_0 == "Isosceles triangle"
    str_1 = module_0.triangle(bool_0, bool_1, bool_2)
    assert str_1 == "Isosceles triangle"


def test_case_3():
    int_0 = 1449
    bool_0 = True
    int_1 = 963
    str_0 = module_0.triangle(int_0, bool_0, int_1)
    assert str_0 == "Scalene triangle"


def test_case_4():
    str_0 = "\\{Hz}NYrP"
    bool_0 = False
    int_0 = 459
    str_1 = module_0.triangle(int_0, bool_0, int_0)
    assert str_1 == "Isosceles triangle"
    str_2 = module_0.triangle(str_0, bool_0, str_0)
    assert str_2 == "Isosceles triangle"
