# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function25 as module_0


def test_case_0():
    bool_0 = True
    var_0 = module_0.reverseNumbers(bool_0)


def test_case_1():
    float_0 = -550.22
    var_0 = module_0.reverseNumbers(float_0)
    var_1 = module_0.reverseNumbers(float_0)
    var_2 = module_0.reverseNumbers(float_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    module_0.reverseNumbers(set_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 1916
    var_0 = module_0.reverseNumbers(int_0)
    int_1 = -3725
    var_1 = module_0.reverseNumbers(int_1)
    module_0.reverseNumbers(var_1)
