# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function48 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    none_type_0 = None
    var_0 = module_0.generateArmstrongNumbers(bool_0, bool_0)
    module_0.generateArmstrongNumbers(bool_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    none_type_0 = None
    module_0.generateArmstrongNumbers(bool_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 535
    var_0 = module_0.generateArmstrongNumbers(int_0, int_0)
    module_0.generateArmstrongNumbers(var_0, var_0)
