# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function35 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    set_0 = set()
    var_0 = module_0.setCommonElements(set_0, set_0)
    none_type_0 = None
    module_0.setCommonElements(none_type_0, set_0)


def test_case_1():
    str_0 = "b\x0cQUer^0YPv.\x0bz"
    set_0 = {str_0}
    var_0 = module_0.setCommonElements(set_0, set_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = True
    module_0.setCommonElements(bool_0, bool_0)
