# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function42 as module_0


def test_case_0():
    int_0 = 378
    var_0 = module_0.randomString(int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x15\xd1"
    module_0.randomString(bytes_0)
