# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import function24 as module_0


def test_case_0():
    var_0 = module_0.fibonacci()
