# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function5 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 1145
    var_0 = module_0.extract_number(int_0)
    module_0.extract_number(var_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    int_0 = -1183
    var_0 = module_0.extract_number(int_0)
    dict_0 = {int_0: int_0}
    module_0.extract_number(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "%gPog?w$TqR'f xl"
    module_0.extract_number(str_0)
