# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function20 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    var_0 = module_0.sumOfList(bool_0, bool_0)
    assert var_0 == 0
    none_type_0 = None
    module_0.sumOfList(var_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    set_0 = set()
    module_0.sumOfList(set_0, set_0)
