# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import function32 as module_0


def test_case_0():
    str_0 = ")'\t0x#K"
    var_0 = module_0.concatenateLists(str_0, str_0)
