# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function1 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xe1\x0cO"
    module_0.remove_chars(bytes_0, bytes_0)
