# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function34 as module_0


def test_case_0():
    bytes_0 = b"\x8c\x00\xf8T"
    set_0 = {bytes_0, bytes_0, bytes_0}
    var_0 = module_0.remove_value(set_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.remove_value(bool_0, bool_0)


def test_case_2():
    tuple_0 = ()
    var_0 = module_0.remove_value(tuple_0, tuple_0)
    var_1 = module_0.remove_value(var_0, var_0)
    var_2 = module_0.remove_value(var_0, tuple_0)
    bytes_0 = b"\xbf\x81\xa7l\x9b{3\x8d+\x93\x02Y\xea\x83"
    none_type_0 = None
    var_3 = module_0.remove_value(bytes_0, none_type_0)
