# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function17 as module_0


def test_case_0():
    bytes_0 = b"m#lj\xe5\x0c\xd7\x11z\xbfr\x18\xff\x98\x1a\xd7\xfc"
    var_0 = module_0.findRotations(bytes_0)
    assert var_0 == 17


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = ""
    var_0 = module_0.findRotations(str_0)
    assert var_0 == 0
    module_0.findRotations(var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = 3156.39717
    module_0.findRotations(float_0)
