# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import function38 as module_0


def test_case_0():
    str_0 = "$fK-_t"
    var_0 = module_0.checkSameItems(str_0)


def test_case_1():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0]
    var_0 = module_0.checkSameItems(list_0)
