# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function15 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"D\xb0\xdb\xd6\x07\xee"
    module_0.area_cylinder(bytes_0, bytes_0)
