# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function22 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    var_0 = module_0.exponent(bool_0, bool_0)
    module_0.exponent(var_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    dict_0 = {bool_0: bool_0}
    var_0 = module_0.exponent(dict_0, bool_0)
    none_type_0 = None
    module_0.exponent(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "K(U%-M3/0Wd3-Qr"
    module_0.exponent(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    float_0 = 2336.80768
    var_0 = module_0.exponent(float_0, float_0)
    bool_0 = True
    module_0.exponent(bool_0, var_0)
