# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import function37 as module_0


def test_case_0():
    bytes_0 = b"</\xdd\xb7H\xa2\xa1\xb86D\xe6<\xcdH\xda\xe5\xe3\xbc"
    var_0 = module_0.reverseTuple(bytes_0)
    var_1 = module_0.reverseTuple(bytes_0)
