# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import function47 as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.checkTriangle(none_type_0, none_type_0, none_type_0)


def test_case_1():
    int_0 = -934
    set_0 = {int_0}
    var_0 = module_0.checkTriangle(int_0, int_0, set_0)
    var_1 = module_0.checkTriangle(var_0, set_0, set_0)


def test_case_2():
    float_0 = -1145.840781
    none_type_0 = None
    var_0 = module_0.checkTriangle(float_0, float_0, none_type_0)
    var_1 = module_0.checkTriangle(float_0, none_type_0, none_type_0)
    var_2 = module_0.checkTriangle(var_1, float_0, var_1)


def test_case_3():
    int_0 = -3743
    var_0 = module_0.checkTriangle(int_0, int_0, int_0)
    none_type_0 = None
    complex_0 = -985.38321 + 73j
    var_1 = module_0.checkTriangle(complex_0, complex_0, complex_0)
    var_2 = module_0.checkTriangle(complex_0, none_type_0, int_0)
    var_3 = module_0.checkTriangle(none_type_0, var_0, none_type_0)
    var_4 = module_0.checkTriangle(var_1, var_3, complex_0)
    var_5 = module_0.checkTriangle(none_type_0, none_type_0, none_type_0)
