# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function23 as module_0
import builtins as module_1


def test_case_0():
    bool_0 = True
    var_0 = module_0.printPrimeNumbersInRange(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = False
    int_0 = 498
    var_0 = module_0.printPrimeNumbersInRange(bool_0, int_0)
    none_type_0 = None
    object_0 = module_1.object()
    module_0.printPrimeNumbersInRange(object_0, none_type_0)
