# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function41 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "L\n+P<7X`p#\r"
    module_0.pickRandomChar(str_0)
