# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function8 as module_0


def test_case_0():
    float_0 = 1210.796
    var_0 = module_0.prodDigit(float_0)
    assert var_0 == pytest.approx(1.5920000000000982, abs=0.01, rel=0.01)


def test_case_1():
    bool_0 = False
    var_0 = module_0.prodDigit(bool_0)
    assert var_0 == 1


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.prodDigit(none_type_0)
