# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function4 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    float_0 = -4493.9
    list_0 = [float_0]
    var_0 = module_0.first_last_same(list_0)
    assert var_0 is True
    module_0.first_last_same(float_0)


def test_case_1():
    bytes_0 = b"\x90\xbb\xc8\xd3\xf0\xd2\xb8\xec\xc9Xn<\x17\n\xc0"
    var_0 = module_0.first_last_same(bytes_0)
    assert var_0 is False
    bytes_1 = b"Z\xfdC\xc7\x7f\xae'\x92\x8f`5\xcb\t\x87\x8f\x90\xaaG&"
    var_1 = module_0.first_last_same(bytes_1)
    assert var_1 is False


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    module_0.first_last_same(set_0)
