# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import function40 as module_0


def test_case_0():
    var_0 = module_0.generate3IntegersDivisibleBy5()
    var_1 = module_0.generate3IntegersDivisibleBy5()
    var_2 = module_0.generate3IntegersDivisibleBy5()
