# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import function2 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = 4021
    var_0 = module_0.checkPrime(int_0)
    assert var_0 is True
    bool_0 = False
    var_1 = module_0.checkPrime(bool_0)
    set_0 = {bool_0, bool_0, bool_0}
    var_2 = module_0.checkPrime(var_1)
    module_0.checkPrime(set_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    var_0 = module_0.checkPrime(bool_0)
    var_1 = module_0.checkPrime(bool_0)
    var_2 = module_0.checkPrime(bool_0)
    bool_1 = False
    dict_0 = {bool_1: bool_1, bool_1: bool_1, bool_1: bool_1, bool_1: bool_1}
    module_0.checkPrime(dict_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = 1759.023
    module_0.checkPrime(float_0)


def test_case_3():
    int_0 = 4929
    var_0 = module_0.checkPrime(int_0)
    assert var_0 is False
    var_1 = module_0.checkPrime(var_0)
    bool_0 = True
    var_2 = module_0.checkPrime(bool_0)
    bool_1 = True
    var_3 = module_0.checkPrime(bool_1)
    var_4 = module_0.checkPrime(var_3)
    var_5 = module_0.checkPrime(bool_1)
    var_6 = module_0.checkPrime(var_5)
    var_7 = module_0.checkPrime(bool_1)
    var_8 = module_0.checkPrime(var_6)
    var_9 = module_0.checkPrime(var_3)
    var_10 = module_0.checkPrime(bool_1)
    var_11 = module_0.checkPrime(var_7)
    var_12 = module_0.checkPrime(var_10)
    var_13 = module_0.checkPrime(var_11)
    var_14 = module_0.checkPrime(var_12)
    var_15 = module_0.checkPrime(var_11)
    var_16 = module_0.checkPrime(var_14)
    var_17 = module_0.checkPrime(var_7)
    var_18 = module_0.checkPrime(var_7)
    var_19 = module_0.checkPrime(var_18)
    var_20 = module_0.checkPrime(var_7)
    var_21 = module_0.checkPrime(bool_1)
